### ISSUE TITLE
Support py3.12

### ISSUE THREAD

**Issue by chenrui333** [Lykos153/AnnexRemote#83]
I ran into some build failure while trying to build datalad against py3.12

```
/private/tmp/datalad--annexremote-20231017-7776-17vwgn/annexremote-1.6.0/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
      LONG_VERSION_PY['git'] = '''
    Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
        main()
      File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/private/tmp/pip-build-env-1p40k3yw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=['wheel'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/private/tmp/pip-build-env-1p40k3yw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
        self.run_setup()
      File "/private/tmp/pip-build-env-1p40k3yw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
        super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
      File "/private/tmp/pip-build-env-1p40k3yw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
        exec(code, locals())
      File "<string>", line 30, in <module>
      File "/private/tmp/datalad--annexremote-20231017-7776-17vwgn/annexremote-1.6.0/versioneer.py", line [148](https://github.com/Homebrew/homebrew-core/actions/runs/6542328562/job/17765225033?pr=151329#step:3:149)0, in get_version
        return get_versions()["version"]
               ^^^^^^^^^^^^^^
      File "/private/tmp/datalad--annexremote-20231017-7776-17vwgn/annexremote-1.6.0/versioneer.py", line 1412, in get_versions
        cfg = get_config_from_root(root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/private/tmp/datalad--annexremote-20231017-7776-17vwgn/annexremote-1.6.0/versioneer.py", line 342, in get_config_from_root
        parser = configparser.SafeConfigParser()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
    error: subprocess-exited-with-error
```

relates to https://github.com/Homebrew/homebrew-core/pull/151329

**Comment by yarikoptic** [comment]
was addressed by #49
