### ISSUE TITLE
Bug: Missing `annexremote._version` in version 1.6.3

### ISSUE THREAD

**Issue by candleindark** [Lykos153/AnnexRemote#93]
In version 1.6.3, `annexremote` fails to be imported, complaining missing `annexremote._version`.

```
import annexremote
Traceback (most recent call last):
  File "/Users/isaac/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Users/isaac/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/isaac/.pyenv/versions/datalad-registry/lib/python3.9/site-packages/annexremote/__init__.py", line 1, in <module>
    from ._version import version as __version__
  File "/Users/isaac/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'annexremote._version'
```

**Comment by yarikoptic** [comment]
hm, the 2ce7dbc594ea6816ea957a154291bc2648b3f428 RFed away from using versioneer in favor of setuptools_scm .  when I try locally -- all is good, but when I go on github actions - it does not bother to produce that `_version.py`... yet to grasp what is going on

**Comment by yarikoptic** [comment]
Thanks @candleindark for the report!!! AFAIK it was an interaction between two systems for the same purposes... seems to be fixed now. I even ran some datalad tests after upgrade -- looks good but daily cron tests of git-annex and datalad might say different ;)
